# This Dockerfile is here to help with end-to-end testing
# From nebulakit
# $ docker build -f Dockerfile.dev --build-arg PYTHON_VERSION=3.10 -t localhost:30000/nebulakittest:someversion .
# $ docker push localhost:30000/nebulakittest:someversion
# From your test user code
# $ pynebula run --image localhost:30000/nebulakittest:someversion

ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim-buster

MAINTAINER Nebula Team <users@nebula.org>
LABEL org.opencontainers.image.source https://github.com/nebulaclouds/nebulakit

WORKDIR /root

ARG VERSION

COPY . /nebulakit

# Note: Pod tasks should be exposed in the default image
# Note: Some packages will create config files under /home by default, so we need to make sure it's writable
# Note: There are use cases that require reading and writing files under /tmp, so we need to change its permissions.

# Run a series of commands to set up the environment:
# 1. Update and install dependencies.
# 2. Install Nebulakit and its plugins.
# 3. Clean up the apt cache to reduce image size. Reference: https://gist.github.com/marvell/7c812736565928e602c4
# 4. Create a non-root user 'nebulakit' and set appropriate permissions for directories.
RUN apt-get update && apt-get install build-essential vim libmagic1 git -y \
    && pip install --no-cache-dir -e /nebulakit \
    && pip install --no-cache-dir -e /nebulakit/plugins/nebulakit-k8s-pod \
    && pip install --no-cache-dir -e /nebulakit/plugins/nebulakit-deck-standard \
    && pip install --no-cache-dir -e /nebulakit/plugins/nebulakit-flyin \
    && pip install --no-cache-dir scikit-learn \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/ \
    && useradd -u 1000 nebulakit \
    && chown nebulakit: /root \
    && chown nebulakit: /home \
    && :

ENV PYTHONPATH "/nebulakit:/nebulakit/plugins/nebulakit-k8s-pod:/nebulakit/plugins/nebulakit-deck-standard:"

# Switch to the 'nebulakit' user for better security.
USER nebulakit
