import os
import pathlib
import shutil
import tempfile
import typing
from unittest.mock import MagicMock

import pytest

import nebulakit.configuration
from nebulakit.configuration import Image, ImageConfig
from nebulakit.core import context_manager
from nebulakit.core.context_manager import ExecutionState, NebulaContextManager
from nebulakit.core.data_persistence import FileAccessProvider
from nebulakit.core.dynamic_workflow_task import dynamic
from nebulakit.core.task import task
from nebulakit.core.type_engine import TypeEngine
from nebulakit.core.workflow import workflow
from nebulakit.models.core.types import BlobType
from nebulakit.models.literals import LiteralMap
from nebulakit.types.directory.types import NebulaDirectory, NebulaDirToMultipartBlobTransformer


# Fixture that ensures a dummy local file
@pytest.fixture
def local_dummy_directory():
    temp_dir = tempfile.TemporaryDirectory()
    try:
        with open(os.path.join(temp_dir.name, "file"), "w") as tmp:
            tmp.write("Hello world")
        yield temp_dir.name
    finally:
        temp_dir.cleanup()


def test_engine():
    t = NebulaDirectory
    lt = TypeEngine.to_literal_type(t)
    assert lt.blob is not None
    assert lt.blob.dimensionality == BlobType.BlobDimensionality.MULTIPART
    assert lt.blob.format == ""

    t2 = NebulaDirectory["csv"]
    lt = TypeEngine.to_literal_type(t2)
    assert lt.blob is not None
    assert lt.blob.dimensionality == BlobType.BlobDimensionality.MULTIPART
    assert lt.blob.format == "csv"


def test_transformer_to_literal_local():
    random_dir = context_manager.NebulaContext.current_context().file_access.get_random_local_directory()
    fs = FileAccessProvider(local_sandbox_dir=random_dir, raw_output_prefix=os.path.join(random_dir, "raw"))
    ctx = context_manager.NebulaContext.current_context()
    with context_manager.NebulaContextManager.with_context(ctx.with_file_access(fs)) as ctx:
        # Use a separate directory that we know won't be the same as anything generated by nebulakit itself, lest we
        # accidentally try to cp -R /some/folder /some/folder/sub which causes exceptions obviously.
        p = "/tmp/nebula/test_fd_transformer"

        # Create an empty directory and call to literal on it
        if os.path.exists(p):
            shutil.rmtree(p)
        pathlib.Path(p).mkdir(parents=True)

        tf = NebulaDirToMultipartBlobTransformer()
        lt = tf.get_literal_type(NebulaDirectory)
        literal = tf.to_literal(ctx, NebulaDirectory(p), NebulaDirectory, lt)
        assert literal.scalar.blob.uri.startswith(random_dir)

        # Create a NebulaDirectory where remote_directory is False
        literal = tf.to_literal(ctx, NebulaDirectory(p, remote_directory=False), NebulaDirectory, lt)
        assert literal.scalar.blob.uri.startswith(p)

        # Create a director with one file in it
        if os.path.exists(p):
            shutil.rmtree(p)
        pathlib.Path(p).mkdir(parents=True)
        with open(os.path.join(p, "xyz"), "w") as fh:
            fh.write("Hello world\n")
        literal = tf.to_literal(ctx, NebulaDirectory(p), NebulaDirectory, lt)

        mock_remote_files = os.listdir(literal.scalar.blob.uri)
        assert mock_remote_files == ["xyz"]

        # The only primitives allowed are strings
        with pytest.raises(AssertionError):
            tf.to_literal(ctx, 3, NebulaDirectory, lt)

        with pytest.raises(TypeError, match="No automatic conversion from <class 'int'>"):
            TypeEngine.to_literal(ctx, 3, NebulaDirectory, lt)


# def test_transformer_to_literal_localss():
#     random_dir = context_manager.NebulaContext.current_context().file_access.get_random_local_directory()
#     fs = FileAccessProvider(local_sandbox_dir=random_dir, raw_output_prefix=os.path.join(random_dir, "raw"))
#     ctx = context_manager.NebulaContext.current_context()
#     with context_manager.NebulaContextManager.with_context(ctx.with_file_access(fs)) as ctx:
#
#         tf = NebulaDirToMultipartBlobTransformer()
#         lt = tf.get_literal_type(NebulaDirectory)
#         # Can't use if it's not a directory
#         with pytest.raises(NebulaAssertion):
#             p = "/tmp/nebula/xyz"
#             path = pathlib.Path(p)
#             try:
#                 path.unlink()
#             except OSError:
#                 ...
#             with open(p, "w") as fh:
#                 fh.write("hello world\n")
#             tf.to_literal(ctx, NebulaDirectory(p), NebulaDirectory, lt)


def test_transformer_to_literal_remote():
    random_dir = context_manager.NebulaContext.current_context().file_access.get_random_local_directory()
    fs = FileAccessProvider(local_sandbox_dir=random_dir, raw_output_prefix=os.path.join(random_dir, "raw"))
    ctx = context_manager.NebulaContext.current_context()
    with context_manager.NebulaContextManager.with_context(ctx.with_file_access(fs)) as ctx:
        # Use a separate directory that we know won't be the same as anything generated by nebulakit itself, lest we
        # accidentally try to cp -R /some/folder /some/folder/sub which causes exceptions obviously.
        p = "/tmp/nebula/test_fd_transformer"
        # Create an empty directory and call to literal on it
        if os.path.exists(p):
            shutil.rmtree(p)
        pathlib.Path(p).mkdir(parents=True)

        tf = NebulaDirToMultipartBlobTransformer()
        lt = tf.get_literal_type(NebulaDirectory)

        # Remote directories should be copied as is.
        literal = tf.to_literal(ctx, NebulaDirectory("s3://anything"), NebulaDirectory, lt)
        assert literal.scalar.blob.uri == "s3://anything"


def test_wf():
    @task
    def t1() -> NebulaDirectory:
        user_ctx = NebulaContextManager.current_context().user_space_params
        # Create a local directory to work with
        p = os.path.join(user_ctx.working_directory, "test_wf")
        if os.path.exists(p):
            shutil.rmtree(p)
        pathlib.Path(p).mkdir(parents=True)
        for i in range(1, 6):
            with open(os.path.join(p, f"{i}.txt"), "w") as fh:
                fh.write(f"I'm file {i}\n")

        return NebulaDirectory(p)

    d = t1()
    files = os.listdir(d.path)
    assert len(files) == 5

    @workflow
    def my_wf() -> NebulaDirectory:
        return t1()

    wfd = my_wf()
    files = os.listdir(wfd.path)
    assert len(files) == 5

    @task
    def t2(in1: NebulaDirectory[typing.TypeVar("csv")]) -> int:
        return len(os.listdir(in1.path))

    @workflow
    def wf2() -> int:
        t1_dir = t1()
        y = t2(in1=t1_dir)
        return y

    x = wf2()
    assert x == 5


def test_dont_convert_remotes():
    @task
    def t1(in1: NebulaDirectory):
        print(in1)

    @dynamic
    def dyn(in1: NebulaDirectory):
        t1(in1=in1)

    fd = NebulaDirectory("s3://anything")

    ctx = context_manager.NebulaContext.current_context()
    with context_manager.NebulaContextManager.with_context(
        ctx.with_serialization_settings(
            nebulakit.configuration.SerializationSettings(
                project="test_proj",
                domain="test_domain",
                version="abc",
                image_config=ImageConfig(Image(name="name", fqn="image", tag="name")),
                env={},
            )
        )
    ) as ctx:
        with context_manager.NebulaContextManager.with_context(
            ctx.with_execution_state(ctx.execution_state.with_params(mode=ExecutionState.Mode.TASK_EXECUTION))
        ) as ctx:
            lit = TypeEngine.to_literal(
                ctx, fd, NebulaDirectory, BlobType("", dimensionality=BlobType.BlobDimensionality.MULTIPART)
            )
            lm = LiteralMap(literals={"in1": lit})
            wf = dyn.dispatch_execute(ctx, lm)
            assert wf.nodes[0].inputs[0].binding.scalar.blob.uri == "s3://anything"


def test_download_caching():
    mock_downloader = MagicMock()
    f = NebulaDirectory("test", mock_downloader)
    assert not f.downloaded
    os.fspath(f)
    assert f.downloaded
    assert mock_downloader.call_count == 1
    for _ in range(10):
        os.fspath(f)
    assert mock_downloader.call_count == 1


def test_returning_a_pathlib_path(local_dummy_directory):
    @task
    def t1() -> NebulaDirectory:
        return pathlib.Path(local_dummy_directory)

    # TODO: Remove this - only here to trigger type engine
    @workflow
    def wf1() -> NebulaDirectory:
        return t1()

    wf_out = wf1()
    assert isinstance(wf_out, NebulaDirectory)
    os.listdir(wf_out)
    assert wf_out._downloaded
    with open(os.path.join(wf_out.path, "file"), "r") as fh:
        assert fh.read() == "Hello world"

    # Remove the file, then call download again, it should not because _downloaded was already set.
    shutil.rmtree(wf_out)
    wf_out.download()
    assert not os.path.exists(wf_out.path)


def test_fd_with_local_remote(local_dummy_directory):
    temp_dir = tempfile.TemporaryDirectory()
    try:

        @task
        def t1() -> NebulaDirectory:
            return NebulaDirectory(local_dummy_directory, remote_directory=temp_dir.name)

        # TODO: Remove this - only here to trigger type engine
        @workflow
        def wf1() -> NebulaDirectory:
            return t1()

        wf_out = wf1()
        files = os.listdir(temp_dir.name)
        assert len(files) == 1  # the pytest fixture has one file in it.
        assert wf_out.path == temp_dir.name
    finally:
        temp_dir.cleanup()


def test_directory_guess():
    transformer = TypeEngine.get_transformer(NebulaDirectory)
    lt = transformer.get_literal_type(NebulaDirectory["txt"])
    assert lt.blob.format == "txt"
    assert lt.blob.dimensionality == 1

    fft = transformer.guess_python_type(lt)
    assert issubclass(fft, NebulaDirectory)
    assert fft.extension() == "txt"

    lt = transformer.get_literal_type(NebulaDirectory)
    assert lt.blob.format == ""
    assert lt.blob.dimensionality == 1

    fft = transformer.guess_python_type(lt)
    assert issubclass(fft, NebulaDirectory)
    assert fft.extension() == ""
