name: Docs Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs_warnings:
    name: Docs Warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Report Sphinx Warnings
        id: sphinx-warnings
        run: |
          sudo apt-get install python3-sphinx  
          python -m pip install tensorflow-macos
          pip install \
            --extra-index-url https://${{ secrets.JFROG_USER}}:${{ secrets.JFROG_PASSWORD }}@streamlineio.jfrog.io/artifactory/api/pypi/nebula-pypi/simple \
            --index https://pypi.python.org/simple \
            -r doc-requirements.txt
          cd docs && SPHINXOPTS="-W" make html
